export interface ModeType {
  id: number;
  name: string;
  alias?: string[];
  mime?: string;
  mode: string;
  mimes?: string[];
  ext?: string[];
  file?: RegExp;
}

export const modes: ModeType[] = [
  {
    id: 1,
    name: 'APL',
    mime: 'text/apl',
    mode: 'apl',
    ext: ['dyalog', 'apl'],
  },
  {
    id: 2,
    name: 'PGP',
    mimes: ['application/pgp', 'application/pgp-encrypted', 'application/pgp-keys', 'application/pgp-signature'],
    mode: 'asciiarmor',
    ext: ['asc', 'pgp', 'sig'],
  },
  {
    id: 3,
    name: 'ASN.1',
    mime: 'text/x-ttcn-asn',
    mode: 'asn.1',
    ext: ['asn', 'asn1'],
  },
  {
    id: 4,
    name: 'Asterisk',
    mime: 'text/x-asterisk',
    mode: 'asterisk',
    file: /^extensions\.conf$/i,
  },
  {
    id: 5,
    name: 'Brainfuck',
    mime: 'text/x-brainfuck',
    mode: 'brainfuck',
    ext: ['b', 'bf'],
  },
  {
    id: 6,
    name: 'C',
    mime: 'text/x-csrc',
    mode: 'clike',
    ext: ['c', 'h', 'ino'],
  },
  {
    id: 7,
    name: 'C++',
    mime: 'text/x-c++src',
    mode: 'clike',
    ext: ['cpp', 'c++', 'cc', 'cxx', 'hpp', 'h++', 'hh', 'hxx'],
    alias: ['cpp'],
  },
  {
    id: 8,
    name: 'Cobol',
    mime: 'text/x-cobol',
    mode: 'cobol',
    ext: ['cob', 'cpy'],
  },
  {
    id: 9,
    name: 'C#',
    mime: 'text/x-csharp',
    mode: 'clike',
    ext: ['cs'],
    alias: ['csharp', 'cs'],
  },
  {
    id: 10,
    name: 'Clojure',
    mime: 'text/x-clojure',
    mode: 'clojure',
    ext: ['clj', 'cljc', 'cljx'],
  },
  {
    id: 11,
    name: 'ClojureScript',
    mime: 'text/x-clojurescript',
    mode: 'clojure',
    ext: ['cljs'],
  },
  {
    id: 12,
    name: 'Closure Stylesheets (GSS)',
    mime: 'text/x-gss',
    mode: 'css',
    ext: ['gss'],
  },
  {
    id: 13,
    name: 'CMake',
    mime: 'text/x-cmake',
    mode: 'cmake',
    ext: ['cmake', 'cmake.in'],
    file: /^CMakeLists.txt$/,
  },
  {
    id: 14,
    name: 'CoffeeScript',
    mimes: ['application/vnd.coffeescript', 'text/coffeescript', 'text/x-coffeescript'],
    mode: 'coffeescript',
    ext: ['coffee'],
    alias: ['coffee', 'coffee-script'],
  },
  {
    id: 15,
    name: 'Common Lisp',
    mime: 'text/x-common-lisp',
    mode: 'commonlisp',
    ext: ['cl', 'lisp', 'el'],
    alias: ['lisp'],
  },
  {
    id: 16,
    name: 'Cypher',
    mime: 'application/x-cypher-query',
    mode: 'cypher',
    ext: ['cyp', 'cypher'],
  },
  {
    id: 17,
    name: 'Cython',
    mime: 'text/x-cython',
    mode: 'python',
    ext: ['pyx', 'pxd', 'pxi'],
  },
  {
    id: 18,
    name: 'Crystal',
    mime: 'text/x-crystal',
    mode: 'crystal',
    ext: ['cr'],
  },
  {
    id: 19,
    name: 'CSS',
    mime: 'text/css',
    mode: 'css',
    ext: ['css'],
  },
  {
    id: 20,
    name: 'CQL',
    mime: 'text/x-cassandra',
    mode: 'sql',
    ext: ['cql'],
  },
  {
    id: 21,
    name: 'D',
    mime: 'text/x-d',
    mode: 'd',
    ext: ['d'],
  },
  {
    id: 22,
    name: 'Dart',
    mimes: ['application/dart', 'text/x-dart'],
    mode: 'dart',
    ext: ['dart'],
  },
  {
    id: 23,
    name: 'diff',
    mime: 'text/x-diff',
    mode: 'diff',
    ext: ['diff', 'patch'],
  },
  {
    id: 24,
    name: 'Django',
    mime: 'text/x-django',
    mode: 'django',
  },
  {
    id: 25,
    name: 'Dockerfile',
    mime: 'text/x-dockerfile',
    mode: 'dockerfile',
    file: /^Dockerfile$/,
  },
  {
    id: 26,
    name: 'DTD',
    mime: 'application/xml-dtd',
    mode: 'dtd',
    ext: ['dtd'],
  },
  {
    id: 27,
    name: 'Dylan',
    mime: 'text/x-dylan',
    mode: 'dylan',
    ext: ['dylan', 'dyl', 'intr'],
  },
  {
    id: 28,
    name: 'EBNF',
    mime: 'text/x-ebnf',
    mode: 'ebnf',
  },
  {
    id: 29,
    name: 'ECL',
    mime: 'text/x-ecl',
    mode: 'ecl',
    ext: ['ecl'],
  },
  {
    id: 30,
    name: 'edn',
    mime: 'application/edn',
    mode: 'clojure',
    ext: ['edn'],
  },
  {
    id: 31,
    name: 'Eiffel',
    mime: 'text/x-eiffel',
    mode: 'eiffel',
    ext: ['e'],
  },
  {
    id: 32,
    name: 'Elm',
    mime: 'text/x-elm',
    mode: 'elm',
    ext: ['elm'],
  },
  {
    id: 33,
    name: 'Embedded Javascript',
    mime: 'application/x-ejs',
    mode: 'htmlembedded',
    ext: ['ejs'],
  },
  {
    id: 34,
    name: 'Embedded Ruby',
    mime: 'application/x-erb',
    mode: 'htmlembedded',
    ext: ['erb'],
  },
  {
    id: 35,
    name: 'Erlang',
    mime: 'text/x-erlang',
    mode: 'erlang',
    ext: ['erl'],
  },
  {
    id: 36,
    name: 'Esper',
    mime: 'text/x-esper',
    mode: 'sql',
  },
  {
    id: 37,
    name: 'Factor',
    mime: 'text/x-factor',
    mode: 'factor',
    ext: ['factor'],
  },
  {
    id: 38,
    name: 'FCL',
    mime: 'text/x-fcl',
    mode: 'fcl',
  },
  {
    id: 39,
    name: 'Forth',
    mime: 'text/x-forth',
    mode: 'forth',
    ext: ['forth', 'fth', '4th'],
  },
  {
    id: 40,
    name: 'Fortran',
    mime: 'text/x-fortran',
    mode: 'fortran',
    ext: ['f', 'for', 'f77', 'f90', 'f95'],
  },
  {
    id: 41,
    name: 'F#',
    mime: 'text/x-fsharp',
    mode: 'mllike',
    ext: ['fs'],
    alias: ['fsharp'],
  },
  {
    id: 42,
    name: 'Gas',
    mime: 'text/x-gas',
    mode: 'gas',
    ext: ['s'],
  },
  {
    id: 43,
    name: 'Gherkin',
    mime: 'text/x-feature',
    mode: 'gherkin',
    ext: ['feature'],
  },
  {
    id: 44,
    name: 'GitHub Flavored Markdown',
    mime: 'text/x-gfm',
    mode: 'gfm',
    file: /^(readme|contributing|history).md$/i,
  },
  {
    id: 45,
    name: 'Go',
    mime: 'text/x-go',
    mode: 'go',
    ext: ['go'],
  },
  {
    id: 46,
    name: 'Groovy',
    mime: 'text/x-groovy',
    mode: 'groovy',
    ext: ['groovy', 'gradle'],
    file: /^Jenkinsfile$/,
  },
  {
    id: 47,
    name: 'HAML',
    mime: 'text/x-haml',
    mode: 'haml',
    ext: ['haml'],
  },
  {
    id: 48,
    name: 'Haskell',
    mime: 'text/x-haskell',
    mode: 'haskell',
    ext: ['hs'],
  },
  {
    id: 49,
    name: 'Haskell (Literate)',
    mime: 'text/x-literate-haskell',
    mode: 'haskell-literate',
    ext: ['lhs'],
  },
  {
    id: 50,
    name: 'Haxe',
    mime: 'text/x-haxe',
    mode: 'haxe',
    ext: ['hx'],
  },
  {
    id: 51,
    name: 'HXML',
    mime: 'text/x-hxml',
    mode: 'haxe',
    ext: ['hxml'],
  },
  {
    id: 52,
    name: 'ASP.NET',
    mime: 'application/x-aspx',
    mode: 'htmlembedded',
    ext: ['aspx'],
    alias: ['asp', 'aspx'],
  },
  {
    id: 53,
    name: 'HTML',
    mime: 'text/html',
    mode: 'htmlmixed',
    ext: ['html', 'htm', 'handlebars', 'hbs'],
    alias: ['xhtml'],
  },
  {
    id: 54,
    name: 'HTTP',
    mime: 'message/http',
    mode: 'http',
  },
  {
    id: 55,
    name: 'IDL',
    mime: 'text/x-idl',
    mode: 'idl',
    ext: ['pro'],
  },
  {
    id: 56,
    name: 'Pug',
    mime: 'text/x-pug',
    mode: 'pug',
    ext: ['jade', 'pug'],
    alias: ['jade'],
  },
  {
    id: 57,
    name: 'Java',
    mime: 'text/x-java',
    mode: 'clike',
    ext: ['java'],
  },
  {
    id: 58,
    name: 'Java Server Pages',
    mime: 'application/x-jsp',
    mode: 'htmlembedded',
    ext: ['jsp'],
    alias: ['jsp'],
  },
  {
    id: 59,
    name: 'JavaScript',
    mimes: [
      'text/javascript',
      'text/ecmascript',
      'application/javascript',
      'application/x-javascript',
      'application/ecmascript',
    ],
    mode: 'javascript',
    ext: ['js'],
    alias: ['ecmascript', 'js', 'node'],
  },
  {
    id: 60,
    name: 'JSON',
    mimes: ['application/json', 'application/x-json'],
    mode: 'javascript',
    ext: ['json', 'map'],
    alias: ['json5'],
  },
  {
    id: 61,
    name: 'JSON-LD',
    mime: 'application/ld+json',
    mode: 'javascript',
    ext: ['jsonld'],
    alias: ['jsonld'],
  },
  {
    id: 62,
    name: 'JSX',
    mime: 'text/jsx',
    mode: 'jsx',
    ext: ['jsx'],
  },
  {
    id: 63,
    name: 'Jinja2',
    mime: 'text/jinja2',
    mode: 'jinja2',
    ext: ['j2', 'jinja', 'jinja2'],
  },
  {
    id: 64,
    name: 'Julia',
    mime: 'text/x-julia',
    mode: 'julia',
    ext: ['jl'],
  },
  {
    id: 65,
    name: 'Kotlin',
    mime: 'text/x-kotlin',
    mode: 'clike',
    ext: ['kt'],
  },
  {
    id: 66,
    name: 'LESS',
    mime: 'text/x-less',
    mode: 'css',
    ext: ['less'],
  },
  {
    id: 67,
    name: 'LiveScript',
    mime: 'text/x-livescript',
    mode: 'livescript',
    ext: ['ls'],
    alias: ['ls'],
  },
  {
    id: 68,
    name: 'Lua',
    mime: 'text/x-lua',
    mode: 'lua',
    ext: ['lua'],
  },
  {
    id: 69,
    name: 'Markdown',
    mime: 'text/x-markdown',
    mode: 'markdown',
    ext: ['markdown', 'md', 'mkd'],
  },
  {
    id: 70,
    name: 'mIRC',
    mime: 'text/mirc',
    mode: 'mirc',
  },
  {
    id: 71,
    name: 'MariaDB SQL',
    mime: 'text/x-mariadb',
    mode: 'sql',
  },
  {
    id: 72,
    name: 'Mathematica',
    mime: 'text/x-mathematica',
    mode: 'mathematica',
    ext: ['m', 'nb', 'wl', 'wls'],
  },
  {
    id: 73,
    name: 'Modelica',
    mime: 'text/x-modelica',
    mode: 'modelica',
    ext: ['mo'],
  },
  {
    id: 74,
    name: 'MUMPS',
    mime: 'text/x-mumps',
    mode: 'mumps',
    ext: ['mps'],
  },
  {
    id: 75,
    name: 'MS SQL',
    mime: 'text/x-mssql',
    mode: 'sql',
  },
  {
    id: 76,
    name: 'mbox',
    mime: 'application/mbox',
    mode: 'mbox',
    ext: ['mbox'],
  },
  {
    id: 77,
    name: 'MySQL',
    mime: 'text/x-mysql',
    mode: 'sql',
  },
  {
    id: 78,
    name: 'Nginx',
    mime: 'text/x-nginx-conf',
    mode: 'nginx',
    file: /nginx.*\.conf$/i,
  },
  {
    id: 79,
    name: 'NSIS',
    mime: 'text/x-nsis',
    mode: 'nsis',
    ext: ['nsh', 'nsi'],
  },
  {
    id: 80,
    name: 'NTriples',
    mimes: ['application/n-triples', 'application/n-quads', 'text/n-triples'],
    mode: 'ntriples',
    ext: ['nt', 'nq'],
  },
  {
    id: 81,
    name: 'Objective-C',
    mime: 'text/x-objectivec',
    mode: 'clike',
    ext: ['m'],
    alias: ['objective-c', 'objc'],
  },
  {
    id: 82,
    name: 'Objective-C++',
    mime: 'text/x-objectivec++',
    mode: 'clike',
    ext: ['mm'],
    alias: ['objective-c++', 'objc++'],
  },
  {
    id: 83,
    name: 'OCaml',
    mime: 'text/x-ocaml',
    mode: 'mllike',
    ext: ['ml', 'mli', 'mll', 'mly'],
  },
  {
    id: 84,
    name: 'Octave',
    mime: 'text/x-octave',
    mode: 'octave',
    ext: ['m'],
  },
  {
    id: 85,
    name: 'Oz',
    mime: 'text/x-oz',
    mode: 'oz',
    ext: ['oz'],
  },
  {
    id: 86,
    name: 'Pascal',
    mime: 'text/x-pascal',
    mode: 'pascal',
    ext: ['p', 'pas'],
  },
  {
    id: 87,
    name: 'PEG.js',
    mime: 'null',
    mode: 'pegjs',
    ext: ['jsonld'],
  },
  {
    id: 88,
    name: 'Perl',
    mime: 'text/x-perl',
    mode: 'perl',
    ext: ['pl', 'pm'],
  },
  {
    id: 89,
    name: 'PHP',
    mimes: ['text/x-php', 'application/x-httpd-php', 'application/x-httpd-php-open'],
    mode: 'php',
    ext: ['php', 'php3', 'php4', 'php5', 'php7', 'phtml'],
  },
  {
    id: 90,
    name: 'Pig',
    mime: 'text/x-pig',
    mode: 'pig',
    ext: ['pig'],
  },
  {
    id: 91,
    name: 'Plain Text',
    mime: 'text/plain',
    mode: 'null',
    ext: ['txt', 'text', 'conf', 'def', 'list', 'log'],
  },
  {
    id: 92,
    name: 'PLSQL',
    mime: 'text/x-plsql',
    mode: 'sql',
    ext: ['pls'],
  },
  {
    id: 93,
    name: 'PostgreSQL',
    mime: 'text/x-pgsql',
    mode: 'sql',
  },
  {
    id: 94,
    name: 'PowerShell',
    mime: 'application/x-powershell',
    mode: 'powershell',
    ext: ['ps1', 'psd1', 'psm1'],
  },
  {
    id: 95,
    name: 'Properties files',
    mime: 'text/x-properties',
    mode: 'properties',
    ext: ['properties', 'ini', 'in'],
    alias: ['ini', 'properties'],
  },
  {
    id: 96,
    name: 'ProtoBuf',
    mime: 'text/x-protobuf',
    mode: 'protobuf',
    ext: ['proto'],
  },
  {
    id: 97,
    name: 'Python',
    mime: 'text/x-python',
    mode: 'python',
    ext: ['BUILD', 'bzl', 'py', 'pyw'],
    file: /^(BUCK|BUILD)$/,
  },
  {
    id: 98,
    name: 'Puppet',
    mime: 'text/x-puppet',
    mode: 'puppet',
    ext: ['pp'],
  },
  {
    id: 99,
    name: 'Q',
    mime: 'text/x-q',
    mode: 'q',
    ext: ['q'],
  },
  {
    id: 100,
    name: 'R',
    mime: 'text/x-rsrc',
    mode: 'r',
    ext: ['r', 'R'],
    alias: ['rscript'],
  },
  {
    id: 101,
    name: 'reStructuredText',
    mime: 'text/x-rst',
    mode: 'rst',
    ext: ['rst'],
    alias: ['rst'],
  },
  {
    id: 102,
    name: 'RPM Changes',
    mime: 'text/x-rpm-changes',
    mode: 'rpm',
  },
  {
    id: 103,
    name: 'RPM Spec',
    mime: 'text/x-rpm-spec',
    mode: 'rpm',
    ext: ['spec'],
  },
  {
    id: 104,
    name: 'Ruby',
    mime: 'text/x-ruby',
    mode: 'ruby',
    ext: ['rb'],
    alias: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
  },
  {
    id: 105,
    name: 'Rust',
    mime: 'text/x-rustsrc',
    mode: 'rust',
    ext: ['rs'],
  },
  {
    id: 106,
    name: 'SAS',
    mime: 'text/x-sas',
    mode: 'sas',
    ext: ['sas'],
  },
  {
    id: 107,
    name: 'Sass',
    mime: 'text/x-sass',
    mode: 'sass',
    ext: ['sass'],
  },
  {
    id: 108,
    name: 'Scala',
    mime: 'text/x-scala',
    mode: 'clike',
    ext: ['scala'],
  },
  {
    id: 109,
    name: 'Scheme',
    mime: 'text/x-scheme',
    mode: 'scheme',
    ext: ['scm', 'ss'],
  },
  {
    id: 110,
    name: 'SCSS',
    mime: 'text/x-scss',
    mode: 'css',
    ext: ['scss'],
  },
  {
    id: 111,
    name: 'Shell',
    mimes: ['text/x-sh', 'application/x-sh'],
    mode: 'shell',
    ext: ['sh', 'ksh', 'bash'],
    alias: ['bash', 'sh', 'zsh'],
    file: /^PKGBUILD$/,
  },
  {
    id: 112,
    name: 'Sieve',
    mime: 'application/sieve',
    mode: 'sieve',
    ext: ['siv', 'sieve'],
  },
  {
    id: 113,
    name: 'Slim',
    mimes: ['text/x-slim', 'application/x-slim'],
    mode: 'slim',
    ext: ['slim'],
  },
  {
    id: 114,
    name: 'Smalltalk',
    mime: 'text/x-stsrc',
    mode: 'smalltalk',
    ext: ['st'],
  },
  {
    id: 115,
    name: 'Smarty',
    mime: 'text/x-smarty',
    mode: 'smarty',
    ext: ['tpl'],
  },
  {
    id: 116,
    name: 'Solr',
    mime: 'text/x-solr',
    mode: 'solr',
  },
  {
    id: 117,
    name: 'SML',
    mime: 'text/x-sml',
    mode: 'mllike',
    ext: ['sml', 'sig', 'fun', 'smackspec'],
  },
  {
    id: 118,
    name: 'Soy',
    mime: 'text/x-soy',
    mode: 'soy',
    ext: ['soy'],
    alias: ['closure template'],
  },
  {
    id: 119,
    name: 'SPARQL',
    mime: 'application/sparql-query',
    mode: 'sparql',
    ext: ['rq', 'sparql'],
    alias: ['sparul'],
  },
  {
    id: 120,
    name: 'Spreadsheet',
    mime: 'text/x-spreadsheet',
    mode: 'spreadsheet',
    alias: ['excel', 'formula'],
  },
  {
    id: 121,
    name: 'SQL',
    mime: 'text/x-sql',
    mode: 'sql',
    ext: ['sql'],
  },
  {
    id: 122,
    name: 'SQLite',
    mime: 'text/x-sqlite',
    mode: 'sql',
  },
  {
    id: 123,
    name: 'Squirrel',
    mime: 'text/x-squirrel',
    mode: 'clike',
    ext: ['nut'],
  },
  {
    id: 124,
    name: 'Stylus',
    mime: 'text/x-styl',
    mode: 'stylus',
    ext: ['styl'],
  },
  {
    id: 125,
    name: 'Swift',
    mime: 'text/x-swift',
    mode: 'swift',
    ext: ['swift'],
  },
  {
    id: 126,
    name: 'sTeX',
    mime: 'text/x-stex',
    mode: 'stex',
  },
  {
    id: 127,
    name: 'LaTeX',
    mime: 'text/x-latex',
    mode: 'stex',
    ext: ['text', 'ltx', 'tex'],
    alias: ['tex'],
  },
  {
    id: 128,
    name: 'SystemVerilog',
    mime: 'text/x-systemverilog',
    mode: 'verilog',
    ext: ['v', 'sv', 'svh'],
  },
  {
    id: 129,
    name: 'Tcl',
    mime: 'text/x-tcl',
    mode: 'tcl',
    ext: ['tcl'],
  },
  {
    id: 130,
    name: 'Textile',
    mime: 'text/x-textile',
    mode: 'textile',
    ext: ['textile'],
  },
  {
    id: 131,
    name: 'TiddlyWiki',
    mime: 'text/x-tiddlywiki',
    mode: 'tiddlywiki',
  },
  {
    id: 132,
    name: 'Tiki wiki',
    mime: 'text/tiki',
    mode: 'tiki',
  },
  {
    id: 133,
    name: 'TOML',
    mime: 'text/x-toml',
    mode: 'toml',
    ext: ['toml'],
  },
  {
    id: 134,
    name: 'Tornado',
    mime: 'text/x-tornado',
    mode: 'tornado',
  },
  {
    id: 135,
    name: 'troff',
    mime: 'text/troff',
    mode: 'troff',
    ext: ['1', '2', '3', '4', '5', '6', '7', '8', '9'],
  },
  {
    id: 136,
    name: 'TTCN',
    mime: 'text/x-ttcn',
    mode: 'ttcn',
    ext: ['ttcn', 'ttcn3', 'ttcnpp'],
  },
  {
    id: 137,
    name: 'TTCN_CFG',
    mime: 'text/x-ttcn-cfg',
    mode: 'ttcn-cfg',
    ext: ['cfg'],
  },
  {
    id: 138,
    name: 'Turtle',
    mime: 'text/turtle',
    mode: 'turtle',
    ext: ['ttl'],
  },
  {
    id: 139,
    name: 'TypeScript',
    mime: 'application/typescript',
    mode: 'javascript',
    ext: ['ts'],
    alias: ['ts'],
  },
  {
    id: 140,
    name: 'TypeScript-JSX',
    mime: 'text/typescript-jsx',
    mode: 'jsx',
    ext: ['tsx'],
    alias: ['tsx'],
  },
  {
    id: 141,
    name: 'Twig',
    mime: 'text/x-twig',
    mode: 'twig',
  },
  {
    id: 142,
    name: 'Web IDL',
    mime: 'text/x-webidl',
    mode: 'webidl',
    ext: ['webidl'],
  },
  {
    id: 143,
    name: 'VB.NET',
    mime: 'text/x-vb',
    mode: 'vb',
    ext: ['vb'],
  },
  {
    id: 144,
    name: 'VBScript',
    mime: 'text/vbscript',
    mode: 'vbscript',
    ext: ['vbs'],
  },
  {
    id: 145,
    name: 'Velocity',
    mime: 'text/velocity',
    mode: 'velocity',
    ext: ['vtl'],
  },
  {
    id: 146,
    name: 'Verilog',
    mime: 'text/x-verilog',
    mode: 'verilog',
    ext: ['v'],
  },
  {
    id: 147,
    name: 'VHDL',
    mime: 'text/x-vhdl',
    mode: 'vhdl',
    ext: ['vhd', 'vhdl'],
  },
  {
    id: 148,
    name: 'Vue.js Component',
    mimes: ['script/x-vue', 'text/x-vue'],
    mode: 'vue',
    ext: ['vue'],
  },
  {
    id: 149,
    name: 'XML',
    mimes: ['application/xml', 'text/xml'],
    mode: 'xml',
    ext: ['xml', 'xsl', 'xsd', 'svg'],
    alias: ['rss', 'wsdl', 'xsd'],
  },
  {
    id: 150,
    name: 'XQuery',
    mime: 'application/xquery',
    mode: 'xquery',
    ext: ['xy', 'xquery'],
  },
  {
    id: 151,
    name: 'Yacas',
    mime: 'text/x-yacas',
    mode: 'yacas',
    ext: ['ys'],
  },
  {
    id: 152,
    name: 'YAML',
    mimes: ['text/x-yaml', 'text/yaml'],
    mode: 'yaml',
    ext: ['yaml', 'yml'],
    alias: ['yml'],
  },
  {
    id: 153,
    name: 'Z80',
    mime: 'text/x-z80',
    mode: 'z80',
    ext: ['z80'],
  },
  {
    id: 154,
    name: 'mscgen',
    mime: 'text/x-mscgen',
    mode: 'mscgen',
    ext: ['mscgen', 'mscin', 'msc'],
  },
  {
    id: 155,
    name: 'xu',
    mime: 'text/x-xu',
    mode: 'mscgen',
    ext: ['xu'],
  },
  {
    id: 156,
    name: 'msgenny',
    mime: 'text/x-msgenny',
    mode: 'mscgen',
    ext: ['msgenny'],
  },
];

export default modes;
